#!/bin/bash
ARCHIVE="incubating-netbeans-java-9.0-rc1-bin.zip"
GETFROM="https://builds.apache.org/view/Incubator%20Projects/job/incubator-netbeans-release/lastSuccessfulBuild/artifact/dist/"

ARCHIVE="incubating-netbeans-java-9.0-beta-bin.zip"
GETFROM="https://www.apache.org/dyn/closer.cgi/incubator/netbeans/incubating-netbeans-java/incubating-9.0-beta/"

cd /tmp
notify-send -i /usr/share/icons/hicolor/128x128/apps/netbeans.png -a NetBeansDevIncubator "starting download"
wget ${GETFROM}${ARCHIVE}
notify-send -i /usr/share/icons/hicolor/128x128/apps/netbeans.png -a NetBeansDevIncubator "unpacking"
unzip $ARCHIVE
notify-send -i /usr/share/icons/hicolor/128x128/apps/netbeans.png -a NetBeansDevIncubator "prepare to start"
sudo rm -rf  /usr/local/netbeans-incubating
sudo mv netbeans /usr/local/netbeans-incubating
rm $ARCHIVE
netbeans
