#!/bin/sh
NBDIR=`ls -t /usr/local/ | grep netbeans | head -n 1`

if [ -z "$NBDIR" ]
then
    NBDIR=`ls -t ~ | grep netbeans- | head -n 1`
fi

notify-send -i /usr/share/pixmaps/netbeans.png -a NetBeans "$NBDIR starting"

exec /usr/local/$NBDIR/bin/netbeans $1 $2 $3


notify-send -i /usr/share/pixmaps/netbeans.png -a NetBeans "$NBDIR started"



