Document: netbeans-php-support
Title: Debian netbeans-php-support Manual
Author: <insert document author here>
Abstract: This manual describes what netbeans-php-support is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/netbeans-php-support/netbeans-php-support.sgml.gz

Format: postscript
Files: /usr/share/doc/netbeans-php-support/netbeans-php-support.ps.gz

Format: text
Files: /usr/share/doc/netbeans-php-support/netbeans-php-support.text.gz

Format: HTML
Index: /usr/share/doc/netbeans-php-support/html/index.html
Files: /usr/share/doc/netbeans-php-support/html/*.html
